package com.deepprotech.deepproject.common.security;

public enum Permission {
    SYSTEM_ADMIN,
    ORG_CREATE, ORG_READ, ORG_UPDATE, ORG_DELETE, ORG_MEMBER_MANAGE,
    WORKSPACE_CREATE, WORKSPACE_READ, WORKSPACE_UPDATE, WORKSPACE_DELETE, WORKSPACE_MEMBER_MANAGE,
    PROJECT_CREATE, PROJECT_READ, PROJECT_UPDATE, PROJECT_DELETE, PROJECT_MEMBER_MANAGE,
    TASK_CREATE, TASK_READ, TASK_UPDATE, TASK_DELETE, TASK_ASSIGN, TASK_STATUS_CHANGE,
    COMMENT_CREATE, COMMENT_READ, COMMENT_UPDATE_OWN, COMMENT_DELETE_OWN, COMMENT_DELETE_ANY,
    NOTIFICATION_READ, NOTIFICATION_MANAGE
}